# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Enter Image', upload_to=''),
            preserve_default=False,
        ),
    ]
