# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Choose an image', upload_to='blog/static/blog/img/'),
            preserve_default=False,
        ),
    ]
