# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageImport',
            field=models.TextField(default='test', verbose_name=[]),
            preserve_default=False,
        ),
    ]
